sudo: required

language: bash

services:
  - docker

branches:
  only:
  - master

before_install:
  - curl -sL https://github.com/yang-l/docker-in-travis-ci/blob/master/Dockerfile -o Dockerfile

install:
  - docker build -t docker-builder .

script:
  - bash docker-build-base.sh
